---
language: node_js

node_js:
  - 'stable'
  - '8'
  - '6'

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test

notifications:
  email:
    on_success: never
  slack:
    rooms:
      secure: OOKD4ZksqzEBW/A3WRuOToODIxnDITqx+Esu7tdmmYPuQlMYgx4SUHv8j9OM9/ScFJiseeVGSkl45vJrHLLIITX9XSjO1RgiGZgw2heVujmGpF6CZNqvT6GsQuKIvMzmwF7IxuHdfV45Csr9Ou/Fg74TszR/4S2h4SOI4zhLg7A=
    on_success: never
