---
language: node_js
node_js:
  - "stable"
  - "10"
  - "12"

dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive

script:
  - yarn test

notifications:
  email:
    on_success: never
  slack:
    rooms:
      secure: OOKD4ZksqzEBW/A3WRuOToODIxnDITqx+Esu7tdmmYPuQlMYgx4SUHv8j9OM9/ScFJiseeVGSkl45vJrHLLIITX9XSjO1RgiGZgw2heVujmGpF6CZNqvT6GsQuKIvMzmwF7IxuHdfV45Csr9Ou/Fg74TszR/4S2h4SOI4zhLg7A=
    on_success: never
