version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Run linting
      - run:
          command: yarn test
          name: Run tests
workflows:
  version: 2
  run_test:
    jobs:
      - test:
          context:
            - "github-packages"
